model:
  encoder_size: 128
  num_layers_encoder: 1
  bidirectional_encoder: True
  decoder_size: 128
  num_blocks: 3
  dropout: 0.3
  max_grad_norm: 5.0
  
objective:
  kl_div_scale_max: 0.1
  l2_scale_max: 0.1
  max_at_epoch: 100

data:
  batch_size: 10

run:
  min_epoch: 100
  max_epochs: 250
  n_search_epochs: 20
  overwrite: True